# Docker compose for netflix conductor + elasticsearch + dynomite
version: '2'
services:
  conductor-server:
    environment:
      - CONFIG_PROP=config.properties
    image: patrickbadley/netflix-conductor-server:2.0.1.1-rabbitmq
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    ports:
      - 8080:8080
    links:
      - elasticsearch:es
      - dynomite:dyno1
      - rabbitmq

  conductor-ui:
    environment:
      - WF_SERVER=http://conductor-server:8080/api/
    image: patrickbadley/netflix-conductor-ui:2.0.1.1-rabbitmq
    build:
      context: ../
      dockerfile: docker/ui/Dockerfile
    ports:
      - 5000:5000
    links:
      - conductor-server

  dynomite:
    image: v1r3n/dynomite
    logging:
      driver: none

  elasticsearch:
    image: elasticsearch:5.6.8
    logging:
      driver: none

  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - 8081:8080
      - 5672:5672